import type { TopLevelDataEntry } from "../uncCompletions.type";

export const UNC_TOP_LEVEL_DATA_PART_2 = [
    [
        "mouse1press",
        "input",
        "Dispatches a left mouse button press.",
        "function mouse1press(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse1release",
        "input",
        "Dispatches a left mouse button release.",
        "function mouse1release(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse2click",
        "input",
        "Dispatches a right mouse button click.",
        "function mouse2click(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse2press",
        "input",
        "Dispatches a right mouse button press.",
        "function mouse2press(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse2release",
        "input",
        "Dispatches a right mouse button release.",
        "function mouse2release(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mousemoveabs",
        "input",
        "Moves the mouse cursor to the specified absolute position.",
        "function mousemoveabs(x: number, y: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mousemoverel",
        "input",
        "Adjusts the mouse cursor by the specified relative amount.",
        "function mousemoverel(x: number, y: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mousescroll",
        "input",
        "Dispatches a mouse scroll by the specified number of pixels.",
        "function mousescroll(pixels: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "fireclickdetector",
        "instances",
        'Dispatches a click or hover event to the given ClickDetector. When absent, distance defaults to zero, and event defaults to "MouseClick".',
        "function fireclickdetector(object: ClickDetector, distance: number?, event: string?): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getcallbackvalue",
        "instances",
        "Returns the function assigned to a callback property of object, which cannot be indexed normally.",
        "function getcallbackvalue(object: Instance, property: string): function?",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getconnections",
        "instances",
        "Creates a list of Connection objects for the functions connected to signal.",
        "function getconnections(signal: RBXScriptSignal): {Connection}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getcustomasset",
        "instances",
        "Returns a rbxasset:// content id for the asset located at path, allowing you to use unmoderated assets. Internally, files are copied to the game's content directory.",
        "function getcustomasset(path: string, noCache: boolean): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "gethiddenproperty",
        "instances",
        "Returns the value of a hidden property of object, which cannot be indexed normally.",
        "function gethiddenproperty(object: Instance, property: string): (any, boolean)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "gethui",
        "instances",
        "Returns a hidden GUI container. Should be used as an alternative to CoreGui and PlayerGui.",
        "function gethui(): Folder",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getinstances",
        "instances",
        "Returns a list of every Instance referenced on the client.",
        "function getinstances(): {Instance}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getnilinstances",
        "instances",
        "Like getinstances, but only includes Instances that are not descendants of a service provider.",
        "function getnilinstances(): {Instance}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "isscriptable",
        "instances",
        "Returns whether the given property is scriptable (does not have the notscriptable tag).",
        "function isscriptable(object: Instance, property: string): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "sethiddenproperty",
        "instances",
        "Sets the value of a hidden property of object, which cannot be set normally. Returns whether the property was hidden.",
        "function sethiddenproperty(object: Instance, property: string, value: any): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "setrbxclipboard",
        "instances",
        "Sets the Studio client's clipboard to the given rbxm or rbxmx model data. This allows data from the game to be copied into a Studio client.",
        "function setrbxclipboard(data: string): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "setscriptable",
        "instances",
        "Set whether the given property is scriptable. Returns whether the property was scriptable prior to changing it.",
        "function setscriptable(object: Instance, property: string, value: boolean): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getrawmetatable",
        "metatable",
        "Returns the metatable of object, where the __metatable field would normally lock the metatable.",
        "function getrawmetatable(object: table): table",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "hookmetamethod",
        "metatable",
        "Replaces func with hook internally, where hook will be invoked in place of func when called.",
        "function hookmetamethod(object: table, method: string, hook: function): function",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "getnamecallmethod",
        "metatable",
        "Returns the name of the method that invoked the __namecall metamethod.",
        "function getnamecallmethod(): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "isreadonly",
        "metatable",
        "Returns whether object is frozen or read-only. Identical to table.isfrozen.",
        "function isreadonly(object: table): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "setrawmetatable",
        "metatable",
        "Sets the metatable of object to metatable, where the __metatable field would normally lock the metatable.",
        "function setrawmetatable(object: table, metatable: table): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "setreadonly",
        "metatable",
        "Sets whether object is frozen or read-only.",
        "function setreadonly(object: table, readonly: boolean): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "identifyexecutor",
        "misc",
        "Returns the name and version of the current executor.",
        "function identifyexecutor(): (string, string)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "lz4compress",
        "misc",
        "Compresses data using LZ4 compression.",
        "function lz4compress(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "lz4decompress",
        "misc",
        "Decompresses data using LZ4 compression, with the decompressed size specified by size.",
        "function lz4decompress(data: string, size: number): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "messagebox",
        "misc",
        "Creates a message box with the specified text, caption, and flags. Yields until the message box is closed, and returns the user input code.",
        "function messagebox(text: string, caption: string, flags: number): number",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "queue_on_teleport",
        "misc",
        "Queues the specified script to be executed after the player teleports to a different place.",
        "function queue_on_teleport(code: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "request",
        "misc",
        "Sends an HTTP request using the specified options. Yields until the request is complete, and returns the response.",
        "function request(options: HttpRequest): HttpResponse",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "setclipboard",
        "misc",
        "Copies text to the clipboard.",
        "function setclipboard(text: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "setfpscap",
        "misc",
        "Sets the in-game FPS cap to fps. If fps is 0, the FPS cap is disabled.",
        "function setfpscap(fps: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
] as const satisfies readonly TopLevelDataEntry[];
