import {
    createLuauLanguageCompletionItem as createItem,
    createLuauNamespaceCompletionGroup as createNamespaceGroup,
} from "../../../../lib/luau/completion/completionBuilder";
import type { LuauNamespaceCompletionGroup } from "../../../../lib/luau/luau.type";
import { LUAU_DOC_SOURCE, ROBLOX_DOC_SOURCE } from "../luauCompletionSources";

export const LUAU_MATH_NAMESPACE_COMPLETION: LuauNamespaceCompletionGroup =
    createNamespaceGroup("math", [
        createItem(
            "abs",
            "function",
            "math function",
            "Return absolute value.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.abs(x: number) -> number" },
        ),
        createItem(
            "acos",
            "function",
            "math function",
            "Return arc cosine.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.acos(x: number) -> number" },
        ),
        createItem(
            "asin",
            "function",
            "math function",
            "Return arc sine.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.asin(x: number) -> number" },
        ),
        createItem(
            "atan",
            "function",
            "math function",
            "Return arc tangent.",
            LUAU_DOC_SOURCE,
            {
                namespace: "math",
                signature: "math.atan(y: number, x?: number) -> number",
            },
        ),
        createItem(
            "atan2",
            "function",
            "math function",
            "Return the arc tangent from y/x.",
            LUAU_DOC_SOURCE,
            {
                namespace: "math",
                signature: "math.atan2(y: number, x: number) -> number",
            },
        ),
        createItem(
            "ceil",
            "function",
            "math function",
            "Round toward positive infinity.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.ceil(x: number) -> number" },
        ),
        createItem(
            "clamp",
            "function",
            "math function",
            "Clamp a number into a range.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "math",
                signature:
                    "math.clamp(x: number, min: number, max: number) -> number",
            },
        ),
        createItem(
            "cos",
            "function",
            "math function",
            "Return cosine.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.cos(x: number) -> number" },
        ),
        createItem(
            "deg",
            "function",
            "math function",
            "Convert radians to degrees.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.deg(x: number) -> number" },
        ),
        createItem(
            "exp",
            "function",
            "math function",
            "Raise e to a power.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.exp(x: number) -> number" },
        ),
        createItem(
            "floor",
            "function",
            "math function",
            "Round toward negative infinity.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.floor(x: number) -> number" },
        ),
        createItem(
            "fmod",
            "function",
            "math function",
            "Return the remainder of a division.",
            LUAU_DOC_SOURCE,
            {
                namespace: "math",
                signature: "math.fmod(x: number, y: number) -> number",
            },
        ),
        createItem(
            "huge",
            "constant",
            "math constant",
            "Positive infinity constant.",
            LUAU_DOC_SOURCE,
            { namespace: "math" },
        ),
        createItem(
            "log",
            "function",
            "math function",
            "Return logarithm in an optional base.",
            LUAU_DOC_SOURCE,
            {
                namespace: "math",
                signature: "math.log(x: number, base?: number) -> number",
            },
        ),
        createItem(
            "max",
            "function",
            "math function",
            "Return the largest argument.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.max(...number) -> number" },
        ),
        createItem(
            "min",
            "function",
            "math function",
            "Return the smallest argument.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.min(...number) -> number" },
        ),
        createItem(
            "noise",
            "function",
            "math function",
            "Return coherent noise for procedural generation.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "math",
                signature:
                    "math.noise(x: number, y?: number, z?: number) -> number",
            },
        ),
        createItem(
            "pi",
            "constant",
            "math constant",
            "Pi constant.",
            LUAU_DOC_SOURCE,
            { namespace: "math" },
        ),
        createItem(
            "pow",
            "function",
            "math function",
            "Raise a number to a power.",
            LUAU_DOC_SOURCE,
            {
                namespace: "math",
                signature: "math.pow(x: number, y: number) -> number",
            },
        ),
        createItem(
            "rad",
            "function",
            "math function",
            "Convert degrees to radians.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.rad(x: number) -> number" },
        ),
        createItem(
            "random",
            "function",
            "math function",
            "Return a pseudo-random number.",
            LUAU_DOC_SOURCE,
            {
                namespace: "math",
                signature: "math.random(min?: number, max?: number) -> number",
            },
        ),
        createItem(
            "randomseed",
            "function",
            "math function",
            "Seed the pseudo-random number generator.",
            LUAU_DOC_SOURCE,
            {
                namespace: "math",
                signature: "math.randomseed(seed: number) -> ()",
            },
        ),
        createItem(
            "round",
            "function",
            "math function",
            "Round to the nearest integer.",
            ROBLOX_DOC_SOURCE,
            { namespace: "math", signature: "math.round(x: number) -> number" },
        ),
        createItem(
            "sign",
            "function",
            "math function",
            "Return -1, 0, or 1 based on number sign.",
            ROBLOX_DOC_SOURCE,
            { namespace: "math", signature: "math.sign(x: number) -> number" },
        ),
        createItem(
            "sin",
            "function",
            "math function",
            "Return sine.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.sin(x: number) -> number" },
        ),
        createItem(
            "sqrt",
            "function",
            "math function",
            "Return square root.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.sqrt(x: number) -> number" },
        ),
        createItem(
            "tan",
            "function",
            "math function",
            "Return tangent.",
            LUAU_DOC_SOURCE,
            { namespace: "math", signature: "math.tan(x: number) -> number" },
        ),
    ]);
