import type { SuncGlobalDataEntry } from "./suncCompletions.type";

export const SUNC_GLOBAL_DATA_PART_2 = [
    [
        "getsenv",
        "Scripts",
        "getsenv returns the global environment table of a given Script, LocalScript, or ModuleScript.",
        "function getsenv(script: BaseScript | ModuleScript): { [any]: any } | nil",
        "https://docs.sunc.su/Scripts/getsenv",
    ],
    [
        "getthreadidentity",
        "Reflection",
        "getthreadidentity retrieves the running Luau thread's identity.",
        "function getthreadidentity(): number",
        "https://docs.sunc.su/Reflection/getthreadidentity",
    ],
    [
        "hookfunction",
        "Closures",
        "hookfunction allows you to hook a function with another wanted function, returning the original unhooked function.",
        "function hookfunction<A1..., R1..., A2..., R2...>(functionToHook: (A1...) -> R1..., hook: (A2...) -> R2...): (A1...) -> R1...",
        "https://docs.sunc.su/Closures/hookfunction",
    ],
    [
        "hookmetamethod",
        "Closures",
        "hookmetamethod takes any Luau object that can have a metatable, and attempts to hook the specified metamethod of the object.",
        "function hookmetamethod(object: { [any]: any } | Instance | userdata, metamethodName: string, hook: (...any) -> (...any)): (...any) -> (...any)",
        "https://docs.sunc.su/Closures/hookmetamethod",
    ],
    [
        "identifyexecutor",
        "Miscellaneous",
        "identifyexecutor returns the name and version of the currently running executor.",
        "function identifyexecutor(): (string, string)",
        "https://docs.sunc.su/Miscellaneous/identifyexecutor",
    ],
    [
        "iscclosure",
        "Closures",
        "iscclosure checks whether a given function is a C closure or not.",
        "function iscclosure(func: (...any) -> (...any)): boolean",
        "https://docs.sunc.su/Closures/iscclosure",
    ],
    [
        "isexecutorclosure",
        "Closures",
        "isexecutorclosure checks whether a given function is a closure of the executor.",
        "function isexecutorclosure(func: (...any) -> (...any)): boolean",
        "https://docs.sunc.su/Closures/isexecutorclosure",
    ],
    [
        "isfile",
        "Filesystem",
        "isfile checks whether a given path exists and refers to a file.",
        "function isfile(path: string): boolean",
        "https://docs.sunc.su/Filesystem/isfile",
    ],
    [
        "isfolder",
        "Filesystem",
        "isfolder checks whether a given path exists and refers to a folder.",
        "function isfolder(path: string): boolean",
        "https://docs.sunc.su/Filesystem/isfolder",
    ],
    [
        "islclosure",
        "Closures",
        "islclosure checks whether a given function is a Luau closure or not.",
        "function islclosure(func: (...any) -> (...any)): boolean",
        "https://docs.sunc.su/Closures/islclosure",
    ],
    [
        "isreadonly",
        "Metatable",
        "isreadonly checks whether a table is currently set as readonly.",
        "function isreadonly(table: { any }): boolean",
        "https://docs.sunc.su/Metatable/isreadonly",
    ],
    [
        "isrenderobj",
        "Drawing",
        "isrenderobj checks whether a given value is a valid Drawing object.",
        "function isrenderobj(object: any): boolean",
        "https://docs.sunc.su/Drawing/isrenderobj",
    ],
    [
        "isscriptable",
        "Reflection",
        "isscriptable returns whether the given property of an Instance is scriptable.",
        "function isscriptable(object: Instance, property: string): boolean | nil",
        "https://docs.sunc.su/Reflection/isscriptable",
    ],
    [
        "listfiles",
        "Filesystem",
        "listfiles returns an array of strings representing all files and folders within the specified directory.",
        "function listfiles(path: string): { string }",
        "https://docs.sunc.su/Filesystem/listfiles",
    ],
    [
        "loadfile",
        "Filesystem",
        "loadfile compiles the Luau source code from a file and returns the resulting function chunk.",
        "function loadfile<A...>(path: string): ((A...) -> any | nil, string?)",
        "https://docs.sunc.su/Filesystem/loadfile",
    ],
    [
        "loadstring",
        "Closures",
        "loadstring compiles a string of Luau code and returns it as a runnable function.",
        "function loadstring<A...>(source: string, chunkname: string?): (((A...) -> any) | nil, string?)",
        "https://docs.sunc.su/Closures/loadstring",
    ],
    [
        "lz4compress",
        "Encoding",
        "lz4compress compresses a string with the LZ4 compression algorithm.",
        "function lz4compress(data: string): string",
        "https://docs.sunc.su/Encoding/lz4compress",
    ],
    [
        "lz4decompress",
        "Encoding",
        "lz4decompress decompresses a string encoded with the LZ4 compression algorithm back to regular data.",
        "function lz4decompress(data: string): string",
        "https://docs.sunc.su/Encoding/lz4decompress",
    ],
    [
        "makefolder",
        "Filesystem",
        "makefolder creates a folder at the specified path if one does not already exist.",
        "function makefolder(path: string): ()",
        "https://docs.sunc.su/Filesystem/makefolder",
    ],
    [
        "newcclosure",
        "Closures",
        "newcclosure takes any Luau function and wraps it into a C closure.",
        "function newcclosure<A..., R...>(functionToWrap: (A...) -> R...): (A...) -> R...",
        "https://docs.sunc.su/Closures/newcclosure",
    ],
    [
        "readfile",
        "Filesystem",
        "readfile retrieves the contents of a file at the specified path and returns it as a string.",
        "function readfile(path: string): string",
        "https://docs.sunc.su/Filesystem/readfile",
    ],
    [
        "replicatesignal",
        "Signals",
        "replicatesignal replicates a signal to the server with the provided arguments, if possible.",
        "function replicatesignal(signal: RBXScriptSignal, ...: any?)",
        "https://docs.sunc.su/Signals/replicatesignal",
    ],
    [
        "request",
        "Miscellaneous",
        "request sends a HTTP request to the given URL using the provided configuration table.",
        "function request(options: RequestOptions): Response",
        "https://docs.sunc.su/Miscellaneous/request",
    ],
    [
        "restorefunction",
        "Closures",
        "restorefunction restores a hooked function back to the very first original function, even if it has been hooked multiple times.",
        "function restorefunction(functionToRestore: (...any) -> (...any)): ()",
        "https://docs.sunc.su/Closures/restorefunction",
    ],
    [
        "sethiddenproperty",
        "Reflection",
        "sethiddenproperty assigns a value to a hidden or non-scriptable property of an Instance.",
        "function sethiddenproperty(instance: Instance, property_name: string, property_value: any): boolean",
        "https://docs.sunc.su/Reflection/sethiddenproperty",
    ],
    [
        "setrawmetatable",
        "Metatable",
        "setrawmetatable forcibly sets the metatable of a value, bypassing the __metatable protection field.",
        "function setrawmetatable<T>(object: T & ({ any } | userdata), metatable: { any }): T",
        "https://docs.sunc.su/Metatable/setrawmetatable",
    ],
    [
        "setreadonly",
        "Metatable",
        "setreadonly sets whether a table is readonly or writable.",
        "function setreadonly(table: { any }, state: boolean): ()",
        "https://docs.sunc.su/Metatable/setreadonly",
    ],
    [
        "setrenderproperty",
        "Drawing",
        "setrenderproperty assigns a value to a property of a Drawing object.",
        "function setrenderproperty(drawing: Drawing, property: string, value: any): ()",
        "https://docs.sunc.su/Drawing/setrenderproperty",
    ],
    [
        "setscriptable",
        "Reflection",
        "setscriptable toggles the scriptability of a hidden or non-scriptable property on an Instance.",
        "function setscriptable(instance: Instance, property_name: string, state: boolean): boolean | nil",
        "https://docs.sunc.su/Reflection/setscriptable",
    ],
    [
        "setthreadidentity",
        "Reflection",
        "setthreadidentity sets the current Luau thread identity and capabilities matching that identity.",
        "function setthreadidentity(id: number): ()",
        "https://docs.sunc.su/Reflection/setthreadidentity",
    ],
    [
        "writefile",
        "Filesystem",
        "writefile writes data to a file at the specified path. If the file already exists, its contents will be overwritten.",
        "function writefile(path: string, data: string): ()",
        "https://docs.sunc.su/Filesystem/writefile",
    ],
] as const satisfies readonly SuncGlobalDataEntry[];
