import {
    createLuauLanguageCompletionItem as createItem,
    createLuauNamespaceCompletionGroup as createNamespaceGroup,
} from "../../../lib/luau/completionBuilder";
import type { LuauNamespaceCompletionGroup } from "../../../lib/luau/luau.type";
import { ROBLOX_DOC_SOURCE } from "./robloxCompletionSources";

export const ROBLOX_ENUM_NAMESPACE_COMPLETION: LuauNamespaceCompletionGroup =
    createNamespaceGroup("Enum", [
        createItem(
            "AccessoryType",
            "enum",
            "enum",
            "Enum describing accessory categories.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "AutomaticSize",
            "enum",
            "enum",
            "Enum controlling automatic GUI sizing.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "Axis",
            "enum",
            "enum",
            "Enum describing an axis.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "EasingDirection",
            "enum",
            "enum",
            "Enum describing tween easing direction.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "EasingStyle",
            "enum",
            "enum",
            "Enum describing tween easing style.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "FillDirection",
            "enum",
            "enum",
            "Enum describing UI fill direction.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "Font",
            "enum",
            "enum",
            "Enum describing built-in font faces.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "FontWeight",
            "enum",
            "enum",
            "Enum describing font weight.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "HorizontalAlignment",
            "enum",
            "enum",
            "Enum describing horizontal UI alignment.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "HumanoidStateType",
            "enum",
            "enum",
            "Enum describing humanoid states.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "KeyCode",
            "enum",
            "enum",
            "Enum describing keyboard and controller key codes.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "Material",
            "enum",
            "enum",
            "Enum describing Roblox material types.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "PlaybackState",
            "enum",
            "enum",
            "Enum describing tween, animation, or sound playback state.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "RaycastFilterType",
            "enum",
            "enum",
            "Enum describing raycast inclusion/exclusion behavior.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "SortOrder",
            "enum",
            "enum",
            "Enum describing sort order behavior.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "TextXAlignment",
            "enum",
            "enum",
            "Enum describing horizontal text alignment.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "TextYAlignment",
            "enum",
            "enum",
            "Enum describing vertical text alignment.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "UserInputType",
            "enum",
            "enum",
            "Enum describing the source device for user input.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "VerticalAlignment",
            "enum",
            "enum",
            "Enum describing vertical UI alignment.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
    ]);
