import { createLuauLanguageCompletionItem as createItem } from "../../../lib/luau/completion/completionBuilder";
import type { LuauCompletionItem } from "../../../lib/luau/luau.type";
import { ROBLOX_DOC_SOURCE } from "./robloxCompletionSources";

export const ROBLOX_TOP_LEVEL_COMPLETIONS_PART_2: LuauCompletionItem[] = [
    createItem(
        "LocalizationService",
        "service",
        "service",
        "Service for localization metadata and translation flows.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "MarketplaceService",
        "service",
        "service",
        "Service for game passes, assets, and purchases.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "PathfindingService",
        "service",
        "service",
        "Service for pathfinding queries.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Players",
        "service",
        "service",
        "Service managing players in the experience.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ReplicatedFirst",
        "service",
        "service",
        "Service containing first-loaded replicated content.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ReplicatedStorage",
        "service",
        "service",
        "Service for replicated shared assets and modules.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "RunService",
        "service",
        "service",
        "Service for heartbeat, stepped, and render loop timing.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ServerScriptService",
        "service",
        "service",
        "Server-only script container service.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ServerStorage",
        "service",
        "service",
        "Server-only asset storage service.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "SoundService",
        "service",
        "service",
        "Service controlling global sound behavior.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "StarterGui",
        "service",
        "service",
        "Service containing initial GUI objects.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "StarterPack",
        "service",
        "service",
        "Service containing starter tools.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "StarterPlayer",
        "service",
        "service",
        "Service containing starter player configuration.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Teams",
        "service",
        "service",
        "Service managing team instances.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "TeleportService",
        "service",
        "service",
        "Service for teleporting players between places.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "TextService",
        "service",
        "service",
        "Service for text filtering and metrics.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "TweenService",
        "service",
        "service",
        "Service for tween creation and playback.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "UserInputService",
        "service",
        "service",
        "Service exposing raw user input state.",
        ROBLOX_DOC_SOURCE,
    ),
];
