import { createLuauLanguageCompletionItem as createItem } from "../../../lib/luau/completion/completionBuilder";
import type { LuauCompletionItem } from "../../../lib/luau/luau.type";
import { LUAU_DOC_SOURCE } from "./luauCompletionSources";

export const LUAU_TOP_LEVEL_COMPLETIONS: LuauCompletionItem[] = [
    createItem(
        "_G",
        "constant",
        "global",
        "Global environment table.",
        LUAU_DOC_SOURCE,
    ),
    createItem(
        "_VERSION",
        "constant",
        "global",
        "Language version string exposed by the runtime.",
        LUAU_DOC_SOURCE,
    ),
    createItem(
        "assert",
        "function",
        "global function",
        "Raise an error if a condition is falsy.",
        LUAU_DOC_SOURCE,
        { signature: "assert(value: any, message?: string) -> any" },
    ),
    createItem(
        "error",
        "function",
        "global function",
        "Raise a runtime error with the provided message or value.",
        LUAU_DOC_SOURCE,
        { signature: "error(message: any, level?: number) -> never" },
    ),
    createItem(
        "getmetatable",
        "function",
        "global function",
        "Return the metatable for a value if it exists.",
        LUAU_DOC_SOURCE,
        { signature: "getmetatable(value: any) -> table?" },
    ),
    createItem(
        "ipairs",
        "function",
        "global function",
        "Iterate over an array-like table in numeric order.",
        LUAU_DOC_SOURCE,
        { signature: "ipairs(list: table) -> iterator" },
    ),
    createItem(
        "next",
        "function",
        "global function",
        "Advance table iteration manually.",
        LUAU_DOC_SOURCE,
        { signature: "next(table: table, index?: any) -> (any, any)" },
    ),
    createItem(
        "pairs",
        "function",
        "global function",
        "Iterate over key/value pairs in a table.",
        LUAU_DOC_SOURCE,
        { signature: "pairs(map: table) -> iterator" },
    ),
    createItem(
        "pcall",
        "function",
        "global function",
        "Call a function in protected mode and capture runtime errors.",
        LUAU_DOC_SOURCE,
        {
            signature:
                "pcall(fn: (...any) -> ...any, ...any) -> (boolean, ...any)",
        },
    ),
    createItem(
        "print",
        "function",
        "global function",
        "Write values to the output stream.",
        LUAU_DOC_SOURCE,
        { signature: "print(...any) -> ()" },
    ),
    createItem(
        "raweq",
        "function",
        "global function",
        "Compare two values without invoking metamethods.",
        LUAU_DOC_SOURCE,
        { signature: "raweq(a: any, b: any) -> boolean" },
    ),
    createItem(
        "rawget",
        "function",
        "global function",
        "Read a table field without invoking metamethods.",
        LUAU_DOC_SOURCE,
        { signature: "rawget(table: table, key: any) -> any" },
    ),
    createItem(
        "rawlen",
        "function",
        "global function",
        "Return the raw length of a table or string.",
        LUAU_DOC_SOURCE,
        { signature: "rawlen(value: table | string) -> number" },
    ),
    createItem(
        "rawset",
        "function",
        "global function",
        "Write a table field without invoking metamethods.",
        LUAU_DOC_SOURCE,
        { signature: "rawset(table: table, key: any, value: any) -> table" },
    ),
    createItem(
        "select",
        "function",
        "global function",
        "Access variadic function arguments.",
        LUAU_DOC_SOURCE,
        { signature: 'select(index: number | "#", ...any) -> any' },
    ),
    createItem(
        "setmetatable",
        "function",
        "global function",
        "Attach a metatable to a table value.",
        LUAU_DOC_SOURCE,
        { signature: "setmetatable(table: table, metatable: table?) -> table" },
    ),
    createItem(
        "tonumber",
        "function",
        "global function",
        "Convert a value to a number if possible.",
        LUAU_DOC_SOURCE,
        { signature: "tonumber(value: any, base?: number) -> number?" },
    ),
    createItem(
        "tostring",
        "function",
        "global function",
        "Convert a value to a string representation.",
        LUAU_DOC_SOURCE,
        { signature: "tostring(value: any) -> string" },
    ),
    createItem(
        "type",
        "function",
        "global function",
        "Return the basic Lua type name for a value.",
        LUAU_DOC_SOURCE,
        { signature: "type(value: any) -> string" },
    ),
    createItem(
        "typeof",
        "function",
        "global function",
        "Return the Luau or platform-specific type name for a value.",
        LUAU_DOC_SOURCE,
        { signature: "typeof(value: any) -> string" },
    ),
    createItem(
        "unpack",
        "function",
        "global function",
        "Expand sequential table values into multiple results.",
        LUAU_DOC_SOURCE,
        { signature: "unpack(list: table, i?: number, j?: number) -> ...any" },
    ),
    createItem(
        "warn",
        "function",
        "global function",
        "Write a warning message to output.",
        LUAU_DOC_SOURCE,
        { signature: "warn(...any) -> ()" },
    ),
    createItem(
        "xpcall",
        "function",
        "global function",
        "Call a function in protected mode with a custom error handler.",
        LUAU_DOC_SOURCE,
        {
            signature:
                "xpcall(fn: (...any) -> ...any, err: (any) -> any, ...any) -> (boolean, ...any)",
        },
    ),
    createItem(
        "bit32",
        "library",
        "library",
        "Bitwise helpers exposed as a standard Luau library.",
        LUAU_DOC_SOURCE,
    ),
    createItem(
        "buffer",
        "library",
        "library",
        "Binary buffer library for fixed-size byte storage and access.",
        LUAU_DOC_SOURCE,
    ),
    createItem(
        "coroutine",
        "library",
        "library",
        "Coroutine creation, scheduling, and inspection helpers.",
        LUAU_DOC_SOURCE,
    ),
    createItem(
        "math",
        "library",
        "library",
        "Math constants and numeric utility functions.",
        LUAU_DOC_SOURCE,
    ),
    createItem(
        "os",
        "library",
        "library",
        "Time and locale-related standard library functions.",
        LUAU_DOC_SOURCE,
    ),
    createItem(
        "string",
        "library",
        "library",
        "String formatting, matching, and manipulation helpers.",
        LUAU_DOC_SOURCE,
    ),
    createItem(
        "table",
        "library",
        "library",
        "Table construction and manipulation helpers.",
        LUAU_DOC_SOURCE,
    ),
    createItem(
        "utf8",
        "library",
        "library",
        "UTF-8 aware string utilities.",
        LUAU_DOC_SOURCE,
    ),
];
