import { createLuauLanguageCompletionItem as createItem } from "../../lib/luau/completionBuilder";
import type { LuauCompletionItem } from "../../lib/luau/luau.type";
import { ROBLOX_DOC_SOURCE } from "./robloxCompletionSources";

export const ROBLOX_TOP_LEVEL_COMPLETIONS_PART_1: LuauCompletionItem[] = [
    createItem(
        "game",
        "namespace",
        "global",
        "Root DataModel for the running Roblox experience.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "workspace",
        "namespace",
        "global",
        "The 3D world container and default Workspace service global.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "script",
        "constant",
        "global",
        "Reference to the currently running script instance.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "shared",
        "namespace",
        "global",
        "Table shared across scripts in the same runtime context.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "plugin",
        "namespace",
        "global",
        "Plugin context object available to Studio plugin scripts.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Enum",
        "namespace",
        "namespace",
        "Access Roblox enum types through the Enum namespace.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Instance",
        "namespace",
        "namespace",
        "Core Roblox instance constructor namespace.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "task",
        "namespace",
        "namespace",
        "Roblox task scheduler helpers.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Axes",
        "datatype",
        "datatype",
        "Datatype representing a set of axes.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "BrickColor",
        "datatype",
        "datatype",
        "Datatype representing a Roblox brick color.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "CFrame",
        "datatype",
        "datatype",
        "Datatype representing a 3D coordinate frame.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Color3",
        "datatype",
        "datatype",
        "Datatype representing an RGB color.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ColorSequence",
        "datatype",
        "datatype",
        "Datatype representing a gradient over time.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "DateTime",
        "datatype",
        "datatype",
        "Datatype representing a UTC timestamp.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Faces",
        "datatype",
        "datatype",
        "Datatype representing a set of part faces.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Font",
        "datatype",
        "datatype",
        "Datatype representing font selection data.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "NumberRange",
        "datatype",
        "datatype",
        "Datatype representing a numeric range.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "NumberSequence",
        "datatype",
        "datatype",
        "Datatype representing numeric interpolation over time.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "PhysicalProperties",
        "datatype",
        "datatype",
        "Datatype representing custom physical properties.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Random",
        "datatype",
        "datatype",
        "Pseudo-random number generator object.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Ray",
        "datatype",
        "datatype",
        "Datatype representing a ray with origin and direction.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Rect",
        "datatype",
        "datatype",
        "Datatype representing a 2D rectangle.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Region3",
        "datatype",
        "datatype",
        "Datatype representing a 3D region.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "TweenInfo",
        "datatype",
        "datatype",
        "Datatype configuring TweenService playback.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "UDim",
        "datatype",
        "datatype",
        "Datatype representing a scale/offset pair.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "UDim2",
        "datatype",
        "datatype",
        "Datatype representing 2D GUI scale/offset coordinates.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Vector2",
        "datatype",
        "datatype",
        "Datatype representing a 2D vector.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Vector3",
        "datatype",
        "datatype",
        "Datatype representing a 3D vector.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "CollectionService",
        "service",
        "service",
        "Service for tagging instances.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ContextActionService",
        "service",
        "service",
        "Service for binding high-level input actions.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Debris",
        "service",
        "service",
        "Service for scheduled cleanup of instances.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "GuiService",
        "service",
        "service",
        "Service for certain GUI and console interactions.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "HttpService",
        "service",
        "service",
        "Service for HTTP requests and JSON encoding.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Lighting",
        "service",
        "service",
        "Service controlling scene lighting and atmosphere.",
        ROBLOX_DOC_SOURCE,
    ),
];
