import {
    createLuauLanguageCompletionItem as createItem,
    createLuauNamespaceCompletionGroup as createNamespaceGroup,
} from "../../lib/luau/completionBuilder";
import type {
    LuauCompletionItem,
    LuauNamespaceCompletionGroup,
} from "../../lib/luau/luau.type";

const ROBLOX_DOC_SOURCE = "Official Roblox Creator and Engine API docs";
export const ROBLOX_TOP_LEVEL_COMPLETIONS: LuauCompletionItem[] = [
    createItem(
        "game",
        "namespace",
        "global",
        "Root DataModel for the running Roblox experience.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "workspace",
        "namespace",
        "global",
        "The 3D world container and default Workspace service global.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "script",
        "constant",
        "global",
        "Reference to the currently running script instance.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "shared",
        "namespace",
        "global",
        "Table shared across scripts in the same runtime context.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "plugin",
        "namespace",
        "global",
        "Plugin context object available to Studio plugin scripts.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Enum",
        "namespace",
        "namespace",
        "Access Roblox enum types through the Enum namespace.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Instance",
        "class",
        "namespace",
        "Core Roblox instance constructor namespace.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "task",
        "namespace",
        "namespace",
        "Roblox task scheduler helpers.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Axes",
        "datatype",
        "datatype",
        "Datatype representing a set of axes.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "BrickColor",
        "datatype",
        "datatype",
        "Datatype representing a Roblox brick color.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "CFrame",
        "datatype",
        "datatype",
        "Datatype representing a 3D coordinate frame.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Color3",
        "datatype",
        "datatype",
        "Datatype representing an RGB color.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ColorSequence",
        "datatype",
        "datatype",
        "Datatype representing a gradient over time.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "DateTime",
        "datatype",
        "datatype",
        "Datatype representing a UTC timestamp.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Faces",
        "datatype",
        "datatype",
        "Datatype representing a set of part faces.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Font",
        "datatype",
        "datatype",
        "Datatype representing font selection data.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "NumberRange",
        "datatype",
        "datatype",
        "Datatype representing a numeric range.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "NumberSequence",
        "datatype",
        "datatype",
        "Datatype representing numeric interpolation over time.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "PhysicalProperties",
        "datatype",
        "datatype",
        "Datatype representing custom physical properties.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Random",
        "datatype",
        "datatype",
        "Pseudo-random number generator object.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Ray",
        "datatype",
        "datatype",
        "Datatype representing a ray with origin and direction.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Rect",
        "datatype",
        "datatype",
        "Datatype representing a 2D rectangle.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Region3",
        "datatype",
        "datatype",
        "Datatype representing a 3D region.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "TweenInfo",
        "datatype",
        "datatype",
        "Datatype configuring TweenService playback.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "UDim",
        "datatype",
        "datatype",
        "Datatype representing a scale/offset pair.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "UDim2",
        "datatype",
        "datatype",
        "Datatype representing 2D GUI scale/offset coordinates.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Vector2",
        "datatype",
        "datatype",
        "Datatype representing a 2D vector.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Vector3",
        "datatype",
        "datatype",
        "Datatype representing a 3D vector.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "CollectionService",
        "service",
        "service",
        "Service for tagging instances.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ContextActionService",
        "service",
        "service",
        "Service for binding high-level input actions.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Debris",
        "service",
        "service",
        "Service for scheduled cleanup of instances.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "GuiService",
        "service",
        "service",
        "Service for certain GUI and console interactions.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "HttpService",
        "service",
        "service",
        "Service for HTTP requests and JSON encoding.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Lighting",
        "service",
        "service",
        "Service controlling scene lighting and atmosphere.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "LocalizationService",
        "service",
        "service",
        "Service for localization metadata and translation flows.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "MarketplaceService",
        "service",
        "service",
        "Service for game passes, assets, and purchases.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "PathfindingService",
        "service",
        "service",
        "Service for pathfinding queries.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Players",
        "service",
        "service",
        "Service managing players in the experience.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ReplicatedFirst",
        "service",
        "service",
        "Service containing first-loaded replicated content.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ReplicatedStorage",
        "service",
        "service",
        "Service for replicated shared assets and modules.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "RunService",
        "service",
        "service",
        "Service for heartbeat, stepped, and render loop timing.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ServerScriptService",
        "service",
        "service",
        "Server-only script container service.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "ServerStorage",
        "service",
        "service",
        "Server-only asset storage service.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "SoundService",
        "service",
        "service",
        "Service controlling global sound behavior.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "StarterGui",
        "service",
        "service",
        "Service containing initial GUI objects.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "StarterPack",
        "service",
        "service",
        "Service containing starter tools.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "StarterPlayer",
        "service",
        "service",
        "Service containing starter player configuration.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "Teams",
        "service",
        "service",
        "Service managing team instances.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "TeleportService",
        "service",
        "service",
        "Service for teleporting players between places.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "TextService",
        "service",
        "service",
        "Service for text filtering and metrics.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "TweenService",
        "service",
        "service",
        "Service for tween creation and playback.",
        ROBLOX_DOC_SOURCE,
    ),
    createItem(
        "UserInputService",
        "service",
        "service",
        "Service exposing raw user input state.",
        ROBLOX_DOC_SOURCE,
    ),
];

export const ROBLOX_NAMESPACE_COMPLETIONS: LuauNamespaceCompletionGroup[] = [
    createNamespaceGroup("task", [
        createItem(
            "cancel",
            "function",
            "task function",
            "Cancel a scheduled task thread.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "task",
                signature: "task.cancel(thread: thread) -> ()",
            },
        ),
        createItem(
            "defer",
            "function",
            "task function",
            "Schedule work for the next resumption cycle.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "task",
                signature:
                    "task.defer(fn: (...any) -> ...any, ...any) -> thread",
            },
        ),
        createItem(
            "delay",
            "function",
            "task function",
            "Schedule a callback after a delay in seconds.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "task",
                signature:
                    "task.delay(duration: number, fn: (...any) -> ...any, ...any) -> thread",
            },
        ),
        createItem(
            "desynchronize",
            "function",
            "task function",
            "Move execution off the synchronized scheduler lane where supported.",
            ROBLOX_DOC_SOURCE,
            { namespace: "task", signature: "task.desynchronize() -> ()" },
        ),
        createItem(
            "spawn",
            "function",
            "task function",
            "Schedule work asynchronously.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "task",
                signature:
                    "task.spawn(fn: (...any) -> ...any, ...any) -> thread",
            },
        ),
        createItem(
            "synchronize",
            "function",
            "task function",
            "Return execution to the synchronized scheduler lane where supported.",
            ROBLOX_DOC_SOURCE,
            { namespace: "task", signature: "task.synchronize() -> ()" },
        ),
        createItem(
            "wait",
            "function",
            "task function",
            "Yield until the next heartbeat or until a duration passes.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "task",
                signature: "task.wait(duration?: number) -> number",
            },
        ),
    ]),
    createNamespaceGroup("Enum", [
        createItem(
            "AccessoryType",
            "enum",
            "enum",
            "Enum describing accessory categories.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "AutomaticSize",
            "enum",
            "enum",
            "Enum controlling automatic GUI sizing.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "Axis",
            "enum",
            "enum",
            "Enum describing an axis.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "EasingDirection",
            "enum",
            "enum",
            "Enum describing tween easing direction.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "EasingStyle",
            "enum",
            "enum",
            "Enum describing tween easing style.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "FillDirection",
            "enum",
            "enum",
            "Enum describing UI fill direction.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "Font",
            "enum",
            "enum",
            "Enum describing built-in font faces.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "FontWeight",
            "enum",
            "enum",
            "Enum describing font weight.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "HorizontalAlignment",
            "enum",
            "enum",
            "Enum describing horizontal UI alignment.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "HumanoidStateType",
            "enum",
            "enum",
            "Enum describing humanoid states.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "KeyCode",
            "enum",
            "enum",
            "Enum describing keyboard and controller key codes.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "Material",
            "enum",
            "enum",
            "Enum describing Roblox material types.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "PlaybackState",
            "enum",
            "enum",
            "Enum describing tween, animation, or sound playback state.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "RaycastFilterType",
            "enum",
            "enum",
            "Enum describing raycast inclusion/exclusion behavior.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "SortOrder",
            "enum",
            "enum",
            "Enum describing sort order behavior.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "TextXAlignment",
            "enum",
            "enum",
            "Enum describing horizontal text alignment.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "TextYAlignment",
            "enum",
            "enum",
            "Enum describing vertical text alignment.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "UserInputType",
            "enum",
            "enum",
            "Enum describing the source device for user input.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
        createItem(
            "VerticalAlignment",
            "enum",
            "enum",
            "Enum describing vertical UI alignment.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Enum" },
        ),
    ]),
    createNamespaceGroup("Instance", [
        createItem(
            "new",
            "function",
            "constructor",
            "Create a new Roblox instance by class name.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "Instance",
                signature:
                    "Instance.new(className: string, parent?: Instance) -> Instance",
            },
        ),
    ]),
    createNamespaceGroup("Color3", [
        createItem(
            "fromHex",
            "function",
            "constructor",
            "Create a Color3 from a hexadecimal string.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "Color3",
                signature: "Color3.fromHex(hex: string) -> Color3",
            },
        ),
        createItem(
            "fromHSV",
            "function",
            "constructor",
            "Create a Color3 from HSV components.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "Color3",
                signature:
                    "Color3.fromHSV(h: number, s: number, v: number) -> Color3",
            },
        ),
        createItem(
            "fromRGB",
            "function",
            "constructor",
            "Create a Color3 from 0-255 RGB components.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "Color3",
                signature:
                    "Color3.fromRGB(r: number, g: number, b: number) -> Color3",
            },
        ),
        createItem(
            "new",
            "function",
            "constructor",
            "Create a Color3 from 0-1 RGB components.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "Color3",
                signature:
                    "Color3.new(r: number, g: number, b: number) -> Color3",
            },
        ),
    ]),
    createNamespaceGroup("Vector2", [
        createItem(
            "new",
            "function",
            "constructor",
            "Create a 2D vector.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "Vector2",
                signature: "Vector2.new(x: number, y: number) -> Vector2",
            },
        ),
        createItem(
            "one",
            "constant",
            "constant",
            "Unit vector with both components set to 1.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Vector2" },
        ),
        createItem(
            "zero",
            "constant",
            "constant",
            "Zero vector.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Vector2" },
        ),
    ]),
    createNamespaceGroup("Vector3", [
        createItem(
            "new",
            "function",
            "constructor",
            "Create a 3D vector.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "Vector3",
                signature:
                    "Vector3.new(x: number, y: number, z: number) -> Vector3",
            },
        ),
        createItem(
            "one",
            "constant",
            "constant",
            "Unit vector with all components set to 1.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Vector3" },
        ),
        createItem(
            "xAxis",
            "constant",
            "constant",
            "Unit vector on the X axis.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Vector3" },
        ),
        createItem(
            "yAxis",
            "constant",
            "constant",
            "Unit vector on the Y axis.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Vector3" },
        ),
        createItem(
            "zAxis",
            "constant",
            "constant",
            "Unit vector on the Z axis.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Vector3" },
        ),
        createItem(
            "zero",
            "constant",
            "constant",
            "Zero vector.",
            ROBLOX_DOC_SOURCE,
            { namespace: "Vector3" },
        ),
    ]),
    createNamespaceGroup("UDim2", [
        createItem(
            "fromOffset",
            "function",
            "constructor",
            "Create a UDim2 using pixel offsets only.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "UDim2",
                signature: "UDim2.fromOffset(x: number, y: number) -> UDim2",
            },
        ),
        createItem(
            "fromScale",
            "function",
            "constructor",
            "Create a UDim2 using scale components only.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "UDim2",
                signature: "UDim2.fromScale(x: number, y: number) -> UDim2",
            },
        ),
        createItem(
            "new",
            "function",
            "constructor",
            "Create a UDim2 from scale and offset components.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "UDim2",
                signature:
                    "UDim2.new(xScale: number, xOffset: number, yScale: number, yOffset: number) -> UDim2",
            },
        ),
    ]),
    createNamespaceGroup("CFrame", [
        createItem(
            "Angles",
            "function",
            "constructor",
            "Create a rotation CFrame from Euler angles in radians.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "CFrame",
                signature:
                    "CFrame.Angles(rx: number, ry: number, rz: number) -> CFrame",
            },
        ),
        createItem(
            "fromAxisAngle",
            "function",
            "constructor",
            "Create a rotation CFrame from an axis-angle pair.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "CFrame",
                signature:
                    "CFrame.fromAxisAngle(axis: Vector3, angle: number) -> CFrame",
            },
        ),
        createItem(
            "fromEulerAnglesXYZ",
            "function",
            "constructor",
            "Create a rotation CFrame from XYZ Euler angles.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "CFrame",
                signature:
                    "CFrame.fromEulerAnglesXYZ(rx: number, ry: number, rz: number) -> CFrame",
            },
        ),
        createItem(
            "fromMatrix",
            "function",
            "constructor",
            "Create a CFrame from basis vectors.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "CFrame",
                signature:
                    "CFrame.fromMatrix(pos: Vector3, vx: Vector3, vy: Vector3, vz?: Vector3) -> CFrame",
            },
        ),
        createItem(
            "lookAt",
            "function",
            "constructor",
            "Create a CFrame oriented toward a target point.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "CFrame",
                signature:
                    "CFrame.lookAt(at: Vector3, lookAt: Vector3, up?: Vector3) -> CFrame",
            },
        ),
        createItem(
            "new",
            "function",
            "constructor",
            "Create a CFrame from translation or coordinate-frame components.",
            ROBLOX_DOC_SOURCE,
            { namespace: "CFrame", signature: "CFrame.new(...any) -> CFrame" },
        ),
    ]),
    createNamespaceGroup("DateTime", [
        createItem(
            "fromIsoDate",
            "function",
            "constructor",
            "Create a DateTime from an ISO date string.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "DateTime",
                signature: "DateTime.fromIsoDate(value: string) -> DateTime",
            },
        ),
        createItem(
            "fromLocalTime",
            "function",
            "constructor",
            "Create a DateTime from local time components.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "DateTime",
                signature:
                    "DateTime.fromLocalTime(year: number, month: number, day: number, hour?: number, minute?: number, second?: number, millisecond?: number) -> DateTime",
            },
        ),
        createItem(
            "fromUniversalTime",
            "function",
            "constructor",
            "Create a DateTime from UTC time components.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "DateTime",
                signature:
                    "DateTime.fromUniversalTime(year: number, month: number, day: number, hour?: number, minute?: number, second?: number, millisecond?: number) -> DateTime",
            },
        ),
        createItem(
            "fromUnixTimestamp",
            "function",
            "constructor",
            "Create a DateTime from a Unix timestamp.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "DateTime",
                signature:
                    "DateTime.fromUnixTimestamp(seconds: number) -> DateTime",
            },
        ),
        createItem(
            "now",
            "function",
            "constructor",
            "Return the current UTC DateTime.",
            ROBLOX_DOC_SOURCE,
            { namespace: "DateTime", signature: "DateTime.now() -> DateTime" },
        ),
    ]),
    createNamespaceGroup("BrickColor", [
        createItem(
            "new",
            "function",
            "constructor",
            "Create a BrickColor from a name, number, or Color3.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "BrickColor",
                signature: "BrickColor.new(value?: any) -> BrickColor",
            },
        ),
        createItem(
            "palette",
            "function",
            "constructor",
            "Return the built-in BrickColor palette.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "BrickColor",
                signature: "BrickColor.palette(index: number) -> BrickColor",
            },
        ),
        createItem(
            "random",
            "function",
            "constructor",
            "Return a random BrickColor from the palette.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "BrickColor",
                signature: "BrickColor.random() -> BrickColor",
            },
        ),
    ]),
    createNamespaceGroup("Random", [
        createItem(
            "new",
            "function",
            "constructor",
            "Create a pseudo-random generator with an optional seed.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "Random",
                signature: "Random.new(seed?: number) -> Random",
            },
        ),
    ]),
    createNamespaceGroup("TweenInfo", [
        createItem(
            "new",
            "function",
            "constructor",
            "Create tween playback configuration data.",
            ROBLOX_DOC_SOURCE,
            {
                namespace: "TweenInfo",
                signature:
                    "TweenInfo.new(time: number, easingStyle?: Enum.EasingStyle, easingDirection?: Enum.EasingDirection, repeatCount?: number, reverses?: boolean, delayTime?: number) -> TweenInfo",
            },
        ),
    ]),
];
