import type { SuncGlobalDataEntry } from "./suncCompletions.type";

export const SUNC_GLOBAL_DATA_PART_1 = [
    [
        "appendfile",
        "Filesystem",
        "appendfile appends string content to the end of a file at the specified path. If the file does not exist, it will be created.",
        "function appendfile(path: string, contents: string): ()",
        "https://docs.sunc.su/Filesystem/appendfile",
    ],
    [
        "base64decode",
        "Encoding",
        "base64decode decodes a Base64-encoded string back into its original form.",
        "function base64decode(data: string): string",
        "https://docs.sunc.su/Encoding/base64decode",
    ],
    [
        "base64encode",
        "Encoding",
        "base64encode encodes a string with Base64 encoding.",
        "function base64encode(data: string): string",
        "https://docs.sunc.su/Encoding/base64encode",
    ],
    [
        "checkcaller",
        "Closures",
        "checkcaller returns a boolean indicating whether the current function was invoked from the executor's own thread. This is useful for differentiating between your own calls and those made by the game.",
        "function checkcaller(): boolean",
        "https://docs.sunc.su/Closures/checkcaller",
    ],
    [
        "cleardrawcache",
        "Drawing",
        "cleardrawcache removes all active drawing objects created with Drawing.new.",
        "function cleardrawcache(): ()",
        "https://docs.sunc.su/Drawing/cleardrawcache",
    ],
    [
        "clonefunction",
        "Closures",
        "clonefunction creates and returns a new function that has the exact same behaviour as the passed function.",
        "function clonefunction<A..., R...>(functionToClone: (A...) -> R...): (A...) -> R...",
        "https://docs.sunc.su/Closures/clonefunction",
    ],
    [
        "cloneref",
        "Instances",
        "cloneref returns a reference clone of an Instance. The returned object behaves identically to the original but is not strictly equal (==) to it.",
        "function cloneref<T>(object: T & Instance): T",
        "https://docs.sunc.su/Instances/cloneref",
    ],
    [
        "compareinstances",
        "Instances",
        "compareinstances checks if two Instances are equal.",
        "function compareinstances(object1: Instance, object2: Instance): boolean",
        "https://docs.sunc.su/Instances/compareinstances",
    ],
    [
        "delfile",
        "Filesystem",
        "delfile deletes the file at the specified path if it exists.",
        "function delfile(path: string): ()",
        "https://docs.sunc.su/Filesystem/delfile",
    ],
    [
        "delfolder",
        "Filesystem",
        "delfolder deletes the folder at the specified path if it exists.",
        "function delfolder(path: string): ()",
        "https://docs.sunc.su/Filesystem/delfolder",
    ],
    [
        "filtergc",
        "Environment",
        "filtergc allows you to retrieve specific garbage-collected values from Luau's memory, using fine-tuned filters.",
        'declare filtergc: (( filterType: "function", filterOptions: FunctionFilterOptions, returnOne: true) -> AnyFunction? ) & ((( filterType: "function", filterOptions: FunctionFilterOptions, returnOne: false?) -> ( AnyFunction | { AnyFunction } ) )) & (( filterType: "table", filterOptions: TableFilterOptions, returnOne: true) -> { AnyTable? } ) & (( filterType: "table", filterOptions: TableFilterOptions, returnOne: false? ) -> { AnyTable })',
        "https://docs.sunc.su/Environment/filtergc",
    ],
    [
        "fireclickdetector",
        "Instances",
        "fireclickdetector triggers a ClickDetector event. By default, it fires the MouseClick event.",
        "function fireclickdetector(detector: ClickDetector, distance: number?, event: string?): ()",
        "https://docs.sunc.su/Instances/fireclickdetector",
    ],
    [
        "fireproximityprompt",
        "Instances",
        "fireproximityprompt instantly triggers a ProximityPrompt, bypassing its HoldDuration and activation distance.",
        "function fireproximityprompt(prompt: ProximityPrompt): ()",
        "https://docs.sunc.su/Instances/fireproximityprompt",
    ],
    [
        "firesignal",
        "Signals",
        "firesignal invokes all Luau connections connected to a given RBXScriptSignal.",
        "function firesignal(signal: RBXScriptSignal, ...: any?)",
        "https://docs.sunc.su/Signals/firesignal",
    ],
    [
        "firetouchinterest",
        "Instances",
        "firetouchinterest simulates a physical touch event between two BasePart objects. It can emulate both the start and end of a Touched event.",
        "function firetouchinterest(part1: BasePart, part2: BasePart, toggle: boolean | number): ()",
        "https://docs.sunc.su/Instances/firetouchinterest",
    ],
    [
        "getcallbackvalue",
        "Instances",
        "getcallbackvalue retrieves the assigned callback property on an Instance, such as OnInvoke.",
        "function getcallbackvalue(object: Instance, property: string): any | nil",
        "https://docs.sunc.su/Instances/getcallbackvalue",
    ],
    [
        "getcallingscript",
        "Scripts",
        "getcallingscript returns the Script, LocalScript, or ModuleScript that triggered the current code execution.",
        "function getcallingscript(): BaseScript | ModuleScript | nil",
        "https://docs.sunc.su/Scripts/getcallingscript",
    ],
    [
        "getconnections",
        "Signals",
        "getconnections retrieves a list of Connection objects currently attached to a given RBXScriptSignal.",
        "function getconnections(signal: RBXScriptSignal): {Connection}",
        "https://docs.sunc.su/Signals/getconnections",
    ],
    [
        "getcustomasset",
        "Filesystem",
        "getcustomasset returns a content ID that can be used in Roblox APIs for loading audio, meshes, UI images, and other asset types.",
        "function getcustomasset(path: string): string",
        "https://docs.sunc.su/Filesystem/getcustomasset",
    ],
    [
        "getfunctionhash",
        "Closures",
        "getfunctionhash returns the hex-represented SHA384 hash of a provided function's instructions and constants.",
        "function getfunctionhash(functionToHash: (...any) -> (...any)): string",
        "https://docs.sunc.su/Closures/getfunctionhash",
    ],
    [
        "getgc",
        "Environment",
        "getgc returns a list of non-dead garbage-collectable values. These include functions, userdatas, and optionally tables.",
        "declare getgc: ((includeTables: true) -> { { AnyTable } | AnyFunction | userdata }) & ((includeTables: false?) -> { AnyFunction })",
        "https://docs.sunc.su/Environment/getgc",
    ],
    [
        "getgenv",
        "Environment",
        "getgenv returns the executor's global environment table, which is shared across all executor-made threads.",
        "function getgenv(): { any }",
        "https://docs.sunc.su/Environment/getgenv",
    ],
    [
        "gethiddenproperty",
        "Reflection",
        "gethiddenproperty retrieves the value of a hidden or non-scriptable property from a given Instance, even if it would normally throw an error when accessed directly.",
        "function gethiddenproperty(instance: Instance, property_name: string): (any, boolean)",
        "https://docs.sunc.su/Reflection/gethiddenproperty",
    ],
    [
        "gethui",
        "Instances",
        "gethui returns a hidden Instance container used for safely storing UI elements.",
        "function gethui(): BasePlayerGui | Folder",
        "https://docs.sunc.su/Instances/gethui",
    ],
    [
        "getinstances",
        "Instances",
        "getinstances retrieves every Instance from the registry, including instances that are or were parented to nil.",
        "function getinstances(): { Instance }",
        "https://docs.sunc.su/Instances/getinstances",
    ],
    [
        "getloadedmodules",
        "Scripts",
        "getloadedmodules returns a list of all ModuleScript instances that have been loaded.",
        "function getloadedmodules(): { ModuleScript }",
        "https://docs.sunc.su/Scripts/getloadedmodules",
    ],
    [
        "getnamecallmethod",
        "Metatable",
        "getnamecallmethod returns the name of the method that invoked the __namecall metamethod.",
        "function getnamecallmethod(): string?",
        "https://docs.sunc.su/Metatable/getnamecallmethod",
    ],
    [
        "getnilinstances",
        "Instances",
        "getnilinstances returns a list of Instance objects that are currently unparented.",
        "function getnilinstances(): { Instance }",
        "https://docs.sunc.su/Instances/getnilinstances",
    ],
    [
        "getrawmetatable",
        "Metatable",
        "getrawmetatable returns the raw metatable of an object, even if that object has a __metatable field set.",
        "function getrawmetatable(object: { any } | userdata): { [any]: any } | nil",
        "https://docs.sunc.su/Metatable/getrawmetatable",
    ],
    [
        "getreg",
        "Environment",
        "getreg returns the Luau registry table.",
        "function getreg(): { [any]: any }",
        "https://docs.sunc.su/Environment/getreg",
    ],
    [
        "getrenderproperty",
        "Drawing",
        "getrenderproperty retrieves the value of a property from a Drawing object.",
        "function getrenderproperty(drawing: Drawing, property: string): any",
        "https://docs.sunc.su/Drawing/getrenderproperty",
    ],
    [
        "getrenv",
        "Environment",
        "getrenv returns the Roblox global environment, which is used by the entire game.",
        "function getrenv(): { any }",
        "https://docs.sunc.su/Environment/getrenv",
    ],
    [
        "getrunningscripts",
        "Scripts",
        "getrunningscripts returns a list of all running scripts in the caller's global state.",
        "function getrunningscripts(): { BaseScript | ModuleScript }",
        "https://docs.sunc.su/Scripts/getrunningscripts",
    ],
    [
        "getscriptbytecode",
        "Scripts",
        "getscriptbytecode retrieves the bytecode of a LocalScript, ModuleScript, or Script.",
        "function getscriptbytecode(script: BaseScript | ModuleScript): string | nil",
        "https://docs.sunc.su/Scripts/getscriptbytecode",
    ],
    [
        "getscriptclosure",
        "Scripts",
        "getscriptclosure creates and returns a Luau function closure from the compiled bytecode of a Script, LocalScript, or ModuleScript.",
        "function getscriptclosure(script: BaseScript | ModuleScript): (...any) -> (...any) | nil",
        "https://docs.sunc.su/Scripts/getscriptclosure",
    ],
    [
        "getscripthash",
        "Scripts",
        "getscripthash returns a SHA-384 hash in hexadecimal format of the raw bytecode for a given script.",
        "function getscripthash(script: BaseScript | ModuleScript): string | nil",
        "https://docs.sunc.su/Scripts/getscripthash",
    ],
    [
        "getscripts",
        "Scripts",
        "getscripts returns a list of all Script, LocalScript, and ModuleScript instances present.",
        "function getscripts(): { BaseScript | ModuleScript }",
        "https://docs.sunc.su/Scripts/getscripts",
    ],
] as const satisfies readonly SuncGlobalDataEntry[];
