import type { AliasDataEntry } from "./uncCompletions.type";

export const UNC_ALIAS_DATA = [
    [
        "replaceclosure",
        "hookfunction",
        "closures",
        "Replaces func with hook internally, where hook will be invoked in place of func when called.",
        "function hookfunction<T>(func: T, hook: function): T",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "checkclosure",
        "isexecutorclosure",
        "closures",
        "Returns whether or not func was created by the executor.",
        "function isexecutorclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "isourclosure",
        "isexecutorclosure",
        "closures",
        "Returns whether or not func was created by the executor.",
        "function isexecutorclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "consoleclear",
        "rconsoleclear",
        "console",
        "Clears the output of the console window.",
        "function rconsoleclear(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consolecreate",
        "rconsolecreate",
        "console",
        "Opens the console window. Text previously output to the console will not be cleared.",
        "function rconsolecreate(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consoledestroy",
        "rconsoledestroy",
        "console",
        "Closes the console window and clears its output. The title will not be changed.",
        "function rconsoledestroy(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consoleinput",
        "rconsoleinput",
        "console",
        "Waits for the user to input text into the console window. Returns the result.",
        "function rconsoleinput(): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consoleprint",
        "rconsoleprint",
        "console",
        "Prints text to the console window. Does not clear existing text or create a new line.",
        "function rconsoleprint(text: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsolename",
        "rconsolesettitle",
        "console",
        "Sets the title of the console window to title.",
        "function rconsolesettitle(title: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consolesettitle",
        "rconsolesettitle",
        "console",
        "Sets the title of the console window to title.",
        "function rconsolesettitle(title: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "isgameactive",
        "isrbxactive",
        "input",
        "Returns whether the game's window is in focus. Must be true for other input functions to work.",
        "function isrbxactive(): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "getexecutorname",
        "identifyexecutor",
        "misc",
        "Returns the name and version of the current executor.",
        "function identifyexecutor(): (string, string)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "queueonteleport",
        "queue_on_teleport",
        "misc",
        "Queues the specified script to be executed after the player teleports to a different place.",
        "function queue_on_teleport(code: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "http_request",
        "request",
        "misc",
        "Sends an HTTP request using the specified options. Yields until the request is complete, and returns the response.",
        "function request(options: HttpRequest): HttpResponse",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "toclipboard",
        "setclipboard",
        "misc",
        "Copies text to the clipboard.",
        "function setclipboard(text: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "dumpstring",
        "getscriptbytecode",
        "scripts",
        "Returns the raw Luau bytecode of the given script.",
        "function getscriptbytecode(script: LocalScript | ModuleScript): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getscriptfunction",
        "getscriptclosure",
        "scripts",
        "Generates a new closure using the bytecode of script.",
        "function getscriptclosure(script: LocalScript | ModuleScript): function",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getidentity",
        "getthreadidentity",
        "scripts",
        "Returns the identity of the current thread.",
        "function getthreadidentity(): number",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getthreadcontext",
        "getthreadidentity",
        "scripts",
        "Returns the identity of the current thread.",
        "function getthreadidentity(): number",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "setidentity",
        "setthreadidentity",
        "scripts",
        "Sets the current thread identity.",
        "function setthreadidentity(identity: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "setthreadcontext",
        "setthreadidentity",
        "scripts",
        "Sets the current thread identity.",
        "function setthreadidentity(identity: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "base64_encode",
        "crypt.base64encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function crypt.base64encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "base64_decode",
        "crypt.base64decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function crypt.base64decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
] as const satisfies readonly AliasDataEntry[];
