import type {
    LuauCompletionItem,
    LuauNamespaceCompletionGroup,
} from "../../types/luau/editor";

const UNC_DOC_SOURCE = "UNC Naming Standard";

type NamespaceDataEntry = readonly [
    namespace: string,
    memberName: string,
    category: string,
    summary: string,
    signature: string,
    sourceLink: string,
];

type TopLevelDataEntry = readonly [
    label: string,
    category: string,
    summary: string,
    signature: string,
    sourceLink: string,
];

type AliasDataEntry = readonly [
    alias: string,
    canonicalName: string,
    category: string,
    summary: string,
    signature: string,
    sourceLink: string,
];

function normalizeSummary(summary: string): string {
    return summary.replace(/\s+/g, " ").trim();
}

function createItem(
    label: string,
    detail: string,
    summary: string,
    signature: string,
    sourceLink: string,
    options?: {
        insertText?: string;
        kind?: LuauCompletionItem["kind"];
        namespace?: string;
        score?: number;
    },
): LuauCompletionItem {
    return {
        label,
        kind: options?.kind ?? "function",
        detail,
        doc: {
            summary: `${normalizeSummary(summary)} Link: ${sourceLink}`,
            source: UNC_DOC_SOURCE,
            signature,
        },
        insertText: options?.insertText,
        namespace: options?.namespace,
        score: options?.score,
        sourceGroup: "executor",
    };
}

function createAliasItem(
    alias: string,
    canonicalName: string,
    detail: string,
    summary: string,
    signature: string,
    sourceLink: string,
    options?: {
        namespace?: string;
        score?: number;
    },
): LuauCompletionItem {
    return createItem(
        alias,
        detail,
        `Alias of ${canonicalName}. ${summary}`,
        signature,
        sourceLink,
        {
            kind: "function",
            namespace: options?.namespace,
            score: options?.score,
        },
    );
}

function createNamespaceGroup(
    namespace: string,
    items: LuauCompletionItem[],
): LuauNamespaceCompletionGroup {
    return {
        namespace,
        items,
    };
}

const UNC_NAMESPACE_SUMMARIES = [
    [
        "Drawing",
        "Drawing",
        "Create drawing objects and inspect the UNC drawing font table.",
        "namespace Drawing",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "WebSocket",
        "WebSocket",
        "Establish UNC WebSocket connections.",
        "namespace WebSocket",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/WebSocket.md",
    ],
    [
        "cache",
        "cache",
        "Work with UNC instance-cache helpers.",
        "namespace cache",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "crypt",
        "crypt",
        "Use UNC crypt helpers for Base64, AES, hashing, and key generation.",
        "namespace crypt",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "debug",
        "debug",
        "Use the UNC extended debug helpers.",
        "namespace debug",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "base64",
        "crypt",
        "Use the UNC base64 alias namespace.",
        "namespace base64",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "http",
        "misc",
        "Use the UNC HTTP alias namespace.",
        "namespace http",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
] as const satisfies readonly TopLevelDataEntry[];

const UNC_TOP_LEVEL_DATA = [
    [
        "cleardrawcache",
        "Drawing",
        "Destroys every drawing object in the cache. Invalidates references to the drawing objects.",
        "function cleardrawcache(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "getrenderproperty",
        "Drawing",
        "Gets the value of a property of a drawing. Functionally identical to drawing[property].",
        "function getrenderproperty(drawing: Drawing, property: string): any",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "isrenderobj",
        "Drawing",
        "Returns whether the given object is a valid Drawing.",
        "function isrenderobj(object: any): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "setrenderproperty",
        "Drawing",
        "Sets the value of a property of a drawing. Functionally identical to drawing[property] = value.",
        "function setrenderproperty(drawing: Drawing, property: string, value: any): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "cloneref",
        "cache",
        "Returns a copy of the Instance reference to object. This is useful for managing an Instance without directly referencing it.",
        "function cloneref(object: Instance): Instance",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "compareinstances",
        "cache",
        "Returns whether objects a and b both reference the same Instance.",
        "function compareinstances(a: Instance, b: Instance): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "checkcaller",
        "closures",
        "Returns whether the function currently running was called by the executor.",
        "function checkcaller(): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "clonefunction",
        "closures",
        "Generates a new closure based on the bytecode of function func.",
        "clonefunction<T>(func: T): T",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "getcallingscript",
        "closures",
        "Returns the script responsible for the currently running function.",
        "function getcallingscript(): BaseScript",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "hookfunction",
        "closures",
        "Replaces func with hook internally, where hook will be invoked in place of func when called.",
        "function hookfunction<T>(func: T, hook: function): T",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "iscclosure",
        "closures",
        "Returns whether or not func is a closure whose source is written in C.",
        "function iscclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "islclosure",
        "closures",
        "Returns whether or not func is a closure whose source is written in Luau.",
        "function islclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "isexecutorclosure",
        "closures",
        "Returns whether or not func was created by the executor.",
        "function isexecutorclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "loadstring",
        "closures",
        "Generates a chunk from the given source code. The environment of the returned function is the global environment.",
        "function loadstring(source: string, chunkname: string?): (function?, string?)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "newcclosure",
        "closures",
        "Returns a C closure that wraps func. The result is functionally identical to func, but identifies as a C closure, and may have different metadata.",
        "function newcclosure<T>(func: T): T",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "rconsoleclear",
        "console",
        "Clears the output of the console window.",
        "function rconsoleclear(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsolecreate",
        "console",
        "Opens the console window. Text previously output to the console will not be cleared.",
        "function rconsolecreate(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsoledestroy",
        "console",
        "Closes the console window and clears its output. The title will not be changed.",
        "function rconsoledestroy(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsoleinput",
        "console",
        "Waits for the user to input text into the console window. Returns the result.",
        "function rconsoleinput(): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsoleprint",
        "console",
        "Prints text to the console window. Does not clear existing text or create a new line.",
        "function rconsoleprint(text: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsolesettitle",
        "console",
        "Sets the title of the console window to title.",
        "function rconsolesettitle(title: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "readfile",
        "filesystem",
        "Returns the contents of the file located at path.",
        "function readfile(path: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "listfiles",
        "filesystem",
        "Returns a list of files and folders in the folder located at path. The returned list contains whole paths.",
        "function listfiles(path: string): {string}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "writefile",
        "filesystem",
        "Writes data to the file located at path if it is not a folder.",
        "function writefile(path: string, data: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "makefolder",
        "filesystem",
        "Creates a folder at path if it does not already exist.",
        "function makefolder(path: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "appendfile",
        "filesystem",
        "Appends data to the end of the file located at path. Creates the file if it does not exist.",
        "function appendfile(path: string, data: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "isfile",
        "filesystem",
        "Returns whether or not path points to a file.",
        "function isfile(path: string): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "isfolder",
        "filesystem",
        "Returns whether or not path points to a folder.",
        "function isfolder(path: string): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "delfile",
        "filesystem",
        "Removes the file located at path.",
        "function delfile(path: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "delfolder",
        "filesystem",
        "Removes the folder located at path.",
        "function delfolder(path: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "loadfile",
        "filesystem",
        "Generates a chunk from the file located at path. The environment of the returned function is the global environment.",
        "function loadfile(path: string, chunkname: string?): (function?, string?)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "dofile",
        "filesystem",
        "Attempts to load the file located at path and execute it on a new thread.",
        "function dofile(path: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "isrbxactive",
        "input",
        "Returns whether the game's window is in focus. Must be true for other input functions to work.",
        "function isrbxactive(): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse1click",
        "input",
        "Dispatches a left mouse button click.",
        "function mouse1click(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse1press",
        "input",
        "Dispatches a left mouse button press.",
        "function mouse1press(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse1release",
        "input",
        "Dispatches a left mouse button release.",
        "function mouse1release(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse2click",
        "input",
        "Dispatches a right mouse button click.",
        "function mouse2click(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse2press",
        "input",
        "Dispatches a right mouse button press.",
        "function mouse2press(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse2release",
        "input",
        "Dispatches a right mouse button release.",
        "function mouse2release(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mousemoveabs",
        "input",
        "Moves the mouse cursor to the specified absolute position.",
        "function mousemoveabs(x: number, y: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mousemoverel",
        "input",
        "Adjusts the mouse cursor by the specified relative amount.",
        "function mousemoverel(x: number, y: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mousescroll",
        "input",
        "Dispatches a mouse scroll by the specified number of pixels.",
        "function mousescroll(pixels: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "fireclickdetector",
        "instances",
        'Dispatches a click or hover event to the given ClickDetector. When absent, distance defaults to zero, and event defaults to "MouseClick".',
        "function fireclickdetector(object: ClickDetector, distance: number?, event: string?): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getcallbackvalue",
        "instances",
        "Returns the function assigned to a callback property of object, which cannot be indexed normally.",
        "function getcallbackvalue(object: Instance, property: string): function?",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getconnections",
        "instances",
        "Creates a list of Connection objects for the functions connected to signal.",
        "function getconnections(signal: RBXScriptSignal): {Connection}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getcustomasset",
        "instances",
        "Returns a rbxasset:// content id for the asset located at path, allowing you to use unmoderated assets. Internally, files are copied to the game's content directory.",
        "function getcustomasset(path: string, noCache: boolean): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "gethiddenproperty",
        "instances",
        "Returns the value of a hidden property of object, which cannot be indexed normally.",
        "function gethiddenproperty(object: Instance, property: string): (any, boolean)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "gethui",
        "instances",
        "Returns a hidden GUI container. Should be used as an alternative to CoreGui and PlayerGui.",
        "function gethui(): Folder",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getinstances",
        "instances",
        "Returns a list of every Instance referenced on the client.",
        "function getinstances(): {Instance}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getnilinstances",
        "instances",
        "Like getinstances, but only includes Instances that are not descendants of a service provider.",
        "function getnilinstances(): {Instance}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "isscriptable",
        "instances",
        "Returns whether the given property is scriptable (does not have the notscriptable tag).",
        "function isscriptable(object: Instance, property: string): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "sethiddenproperty",
        "instances",
        "Sets the value of a hidden property of object, which cannot be set normally. Returns whether the property was hidden.",
        "function sethiddenproperty(object: Instance, property: string, value: any): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "setrbxclipboard",
        "instances",
        "Sets the Studio client's clipboard to the given rbxm or rbxmx model data. This allows data from the game to be copied into a Studio client.",
        "function setrbxclipboard(data: string): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "setscriptable",
        "instances",
        "Set whether the given property is scriptable. Returns whether the property was scriptable prior to changing it.",
        "function setscriptable(object: Instance, property: string, value: boolean): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/instances.md",
    ],
    [
        "getrawmetatable",
        "metatable",
        "Returns the metatable of object, where the __metatable field would normally lock the metatable.",
        "function getrawmetatable(object: table): table",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "hookmetamethod",
        "metatable",
        "Replaces func with hook internally, where hook will be invoked in place of func when called.",
        "function hookmetamethod(object: table, method: string, hook: function): function",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "getnamecallmethod",
        "metatable",
        "Returns the name of the method that invoked the __namecall metamethod.",
        "function getnamecallmethod(): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "isreadonly",
        "metatable",
        "Returns whether object is frozen or read-only. Identical to table.isfrozen.",
        "function isreadonly(object: table): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "setrawmetatable",
        "metatable",
        "Sets the metatable of object to metatable, where the __metatable field would normally lock the metatable.",
        "function setrawmetatable(object: table, metatable: table): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "setreadonly",
        "metatable",
        "Sets whether object is frozen or read-only.",
        "function setreadonly(object: table, readonly: boolean): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/metatable.md",
    ],
    [
        "identifyexecutor",
        "misc",
        "Returns the name and version of the current executor.",
        "function identifyexecutor(): (string, string)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "lz4compress",
        "misc",
        "Compresses data using LZ4 compression.",
        "function lz4compress(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "lz4decompress",
        "misc",
        "Decompresses data using LZ4 compression, with the decompressed size specified by size.",
        "function lz4decompress(data: string, size: number): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "messagebox",
        "misc",
        "Creates a message box with the specified text, caption, and flags. Yields until the message box is closed, and returns the user input code.",
        "function messagebox(text: string, caption: string, flags: number): number",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "queue_on_teleport",
        "misc",
        "Queues the specified script to be executed after the player teleports to a different place.",
        "function queue_on_teleport(code: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "request",
        "misc",
        "Sends an HTTP request using the specified options. Yields until the request is complete, and returns the response.",
        "function request(options: HttpRequest): HttpResponse",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "setclipboard",
        "misc",
        "Copies text to the clipboard.",
        "function setclipboard(text: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "setfpscap",
        "misc",
        "Sets the in-game FPS cap to fps. If fps is 0, the FPS cap is disabled.",
        "function setfpscap(fps: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "getgc",
        "scripts",
        "Returns a list of objects in the Luau garbage collector.",
        "function getgc(includeTables: boolean?): {function | userdata | table}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getgenv",
        "scripts",
        "Returns the custom global environment of the executor. It can be used to add global functions or share variables between scripts.",
        "function getgenv(): { [string]: any }",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getloadedmodules",
        "scripts",
        "Returns a list of ModuleScripts that have been loaded. If excludeCore is true, CoreScript-related modules will not be included in the list.",
        "function getloadedmodules(excludeCore: boolean?): {ModuleScript}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getrenv",
        "scripts",
        "Returns the global environment of the game client. It can be used to access the global functions that LocalScripts and ModuleScripts use.",
        "function getrenv(): { [string]: any }",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getrunningscripts",
        "scripts",
        "Returns a list of scripts that are currently running.",
        "function getrunningscripts(): {LocalScript | ModuleScript}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getscriptbytecode",
        "scripts",
        "Returns the raw Luau bytecode of the given script.",
        "function getscriptbytecode(script: LocalScript | ModuleScript): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getscriptclosure",
        "scripts",
        "Generates a new closure using the bytecode of script.",
        "function getscriptclosure(script: LocalScript | ModuleScript): function",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getscripthash",
        "scripts",
        "Returns a SHA384 hash of the script's bytecode. This is useful for detecting changes to a script's source code.",
        "function getscripthash(script: LocalScript | ModuleScript): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getscripts",
        "scripts",
        "Returns a list of every script in the game.",
        "function getscripts(): {LocalScript | ModuleScript}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getsenv",
        "scripts",
        "Returns the global environment of the given script. It can be used to access variables and functions that are not defined as local.",
        "function getsenv(script: LocalScript | ModuleScript): { [string]: any }",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getthreadidentity",
        "scripts",
        "Returns the identity of the current thread.",
        "function getthreadidentity(): number",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "setthreadidentity",
        "scripts",
        "Sets the current thread identity.",
        "function setthreadidentity(identity: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
] as const satisfies readonly TopLevelDataEntry[];

const UNC_ALIAS_DATA = [
    [
        "replaceclosure",
        "hookfunction",
        "closures",
        "Replaces func with hook internally, where hook will be invoked in place of func when called.",
        "function hookfunction<T>(func: T, hook: function): T",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "checkclosure",
        "isexecutorclosure",
        "closures",
        "Returns whether or not func was created by the executor.",
        "function isexecutorclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "isourclosure",
        "isexecutorclosure",
        "closures",
        "Returns whether or not func was created by the executor.",
        "function isexecutorclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "consoleclear",
        "rconsoleclear",
        "console",
        "Clears the output of the console window.",
        "function rconsoleclear(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consolecreate",
        "rconsolecreate",
        "console",
        "Opens the console window. Text previously output to the console will not be cleared.",
        "function rconsolecreate(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consoledestroy",
        "rconsoledestroy",
        "console",
        "Closes the console window and clears its output. The title will not be changed.",
        "function rconsoledestroy(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consoleinput",
        "rconsoleinput",
        "console",
        "Waits for the user to input text into the console window. Returns the result.",
        "function rconsoleinput(): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consoleprint",
        "rconsoleprint",
        "console",
        "Prints text to the console window. Does not clear existing text or create a new line.",
        "function rconsoleprint(text: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsolename",
        "rconsolesettitle",
        "console",
        "Sets the title of the console window to title.",
        "function rconsolesettitle(title: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "consolesettitle",
        "rconsolesettitle",
        "console",
        "Sets the title of the console window to title.",
        "function rconsolesettitle(title: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "isgameactive",
        "isrbxactive",
        "input",
        "Returns whether the game's window is in focus. Must be true for other input functions to work.",
        "function isrbxactive(): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "getexecutorname",
        "identifyexecutor",
        "misc",
        "Returns the name and version of the current executor.",
        "function identifyexecutor(): (string, string)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "queueonteleport",
        "queue_on_teleport",
        "misc",
        "Queues the specified script to be executed after the player teleports to a different place.",
        "function queue_on_teleport(code: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "http_request",
        "request",
        "misc",
        "Sends an HTTP request using the specified options. Yields until the request is complete, and returns the response.",
        "function request(options: HttpRequest): HttpResponse",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "toclipboard",
        "setclipboard",
        "misc",
        "Copies text to the clipboard.",
        "function setclipboard(text: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
    [
        "dumpstring",
        "getscriptbytecode",
        "scripts",
        "Returns the raw Luau bytecode of the given script.",
        "function getscriptbytecode(script: LocalScript | ModuleScript): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getscriptfunction",
        "getscriptclosure",
        "scripts",
        "Generates a new closure using the bytecode of script.",
        "function getscriptclosure(script: LocalScript | ModuleScript): function",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getidentity",
        "getthreadidentity",
        "scripts",
        "Returns the identity of the current thread.",
        "function getthreadidentity(): number",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "getthreadcontext",
        "getthreadidentity",
        "scripts",
        "Returns the identity of the current thread.",
        "function getthreadidentity(): number",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "setidentity",
        "setthreadidentity",
        "scripts",
        "Sets the current thread identity.",
        "function setthreadidentity(identity: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "setthreadcontext",
        "setthreadidentity",
        "scripts",
        "Sets the current thread identity.",
        "function setthreadidentity(identity: number): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/scripts.md",
    ],
    [
        "base64_encode",
        "crypt.base64encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function crypt.base64encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "base64_decode",
        "crypt.base64decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function crypt.base64decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
] as const satisfies readonly AliasDataEntry[];

const UNC_NAMESPACE_DATA = [
    [
        "Drawing",
        "new",
        "Drawing",
        "Create a new drawing object of the specified type.",
        "function Drawing.new(type: string): Drawing",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "Drawing",
        "Fonts",
        "Drawing",
        "A table containing the available font names. The style of each font varies depending on the executor.",
        "Drawing.Fonts: { [string]: number }",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "WebSocket",
        "connect",
        "WebSocket",
        "Establishes a WebSocket connection to the specified URL.",
        "function WebSocket.connect(url: string): WebSocket",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/WebSocket.md",
    ],
    [
        "cache",
        "invalidate",
        "cache",
        "Deletes object from the Instance cache. Effectively invalidates object as a reference to the underlying Instance.",
        "function cache.invalidate(object: Instance): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "cache",
        "iscached",
        "cache",
        "Checks whether object exists in the Instance cache.",
        "function cache.iscached(object: Instance): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "cache",
        "replace",
        "cache",
        "Replaces object in the Instance cache with newObject.",
        "function cache.replace(object: Instance, newObject: Instance): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "crypt",
        "base64",
        "crypt",
        "UNC nested namespace for Base64 helpers under crypt.",
        "namespace crypt.base64",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "base64encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function crypt.base64encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "base64decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function crypt.base64decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "base64_encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function crypt.base64encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "base64_decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function crypt.base64decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "encrypt",
        "crypt",
        "Encrypts an unencoded string using AES encryption. Returns the base64 encoded and encrypted string, and the IV.",
        "function crypt.encrypt(data: string, key: string, iv: string?, mode: string?): (string, string)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "decrypt",
        "crypt",
        "Decrypts the base64 encoded and encrypted content. Returns the raw string.",
        "function crypt.decrypt(data: string, key: string, iv: string, mode: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "generatebytes",
        "crypt",
        "Generates a random sequence of bytes of the given size. Returns the sequence as a base64 encoded string.",
        "function crypt.generatebytes(size: number): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "generatekey",
        "crypt",
        "Generates a base64 encoded 256-bit key. The result can be used as the second parameter for the crypt.encrypt and crypt.decrypt functions.",
        "function crypt.generatekey(): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "hash",
        "crypt",
        "Returns the result of hashing the data using the given algorithm.",
        "function crypt.hash(data: string, algorithm: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt.base64",
        "encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function crypt.base64.encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt.base64",
        "decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function crypt.base64.decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "debug",
        "getconstant",
        "debug",
        "Returns the constant at index in the constant table of the function or level func. Throws an error if the constant does not exist.",
        "function debug.getconstant(func: function | number, index: number): any",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getconstants",
        "debug",
        "Returns the constant table of the function or level func.",
        "function debug.getconstants(func: function | number): {any}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getinfo",
        "debug",
        "Returns debugger information about a function or stack level.",
        "function debug.getinfo(func: function | number): DebugInfo",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getproto",
        "debug",
        "Returns the proto at index in the function or level func if active is false.",
        "function debug.getproto(func: function | number, index: number, active: boolean?): function | {function}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getprotos",
        "debug",
        "Returns a list of protos of the function or level func.",
        "function debug.getprotos(func: function | number): {function}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getstack",
        "debug",
        "Returns the value at index in the stack frame level. Throws an error if no value could be found.",
        "function debug.getstack(level: number, index: number?): any | {any}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getupvalue",
        "debug",
        "Returns the upvalue at index in the function or level func. Throws an error if the upvalue does not exist.",
        "function debug.getupvalue(func: function | number, index: number): any",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getupvalues",
        "debug",
        "Returns a list of upvalues of the function or level func.",
        "function debug.getupvalues(func: function | number): {any}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "setconstant",
        "debug",
        "Sets the constant at index in the function or level func to value.",
        "function debug.setconstant(func: function | number, index: number, value: any): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "setstack",
        "debug",
        "Sets the register at index in the stack frame level to value.",
        "function debug.setstack(level: number, index: number, value: any): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "setupvalue",
        "debug",
        "Sets the upvalue at index in the function or level func to value.",
        "function debug.setupvalue(func: function | number, index: number, value: any): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "base64",
        "encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function base64.encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "base64",
        "decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function base64.decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "http",
        "request",
        "misc",
        "Sends an HTTP request using the specified options. Yields until the request is complete, and returns the response.",
        "function http.request(options: HttpRequest): HttpResponse",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
] as const satisfies readonly NamespaceDataEntry[];

export const UNC_GLOBAL_FUNCTION_NAMES = [
    ...UNC_TOP_LEVEL_DATA.map(([label]) => label),
    ...UNC_ALIAS_DATA.map(([alias]) => alias),
] as const;

export const UNC_NAMESPACE_NAMES = Array.from(
    new Set(UNC_NAMESPACE_DATA.map(([namespace]) => namespace.split(".")[0])),
);

export const UNC_TOP_LEVEL_COMPLETIONS: LuauCompletionItem[] = [
    ...UNC_NAMESPACE_SUMMARIES.map(
        ([label, category, summary, signature, link]) =>
            createItem(label, `unc ${category}`, summary, signature, link, {
                kind: "namespace",
                score: 1140,
            }),
    ),
    ...UNC_TOP_LEVEL_DATA.map(([label, category, summary, signature, link]) =>
        createItem(label, `unc ${category}`, summary, signature, link, {
            kind: "function",
            score: 1130,
        }),
    ),
    ...UNC_ALIAS_DATA.map(
        ([alias, canonicalName, category, summary, signature, link]) =>
            createAliasItem(
                alias,
                canonicalName,
                `unc alias (${category})`,
                summary,
                signature,
                link,
                { score: 1110 },
            ),
    ),
];

export const UNC_NAMESPACE_COMPLETIONS: LuauNamespaceCompletionGroup[] =
    Array.from(new Set(UNC_NAMESPACE_DATA.map(([namespace]) => namespace))).map(
        (namespace) =>
            createNamespaceGroup(
                namespace,
                UNC_NAMESPACE_DATA.filter(
                    ([candidateNamespace]) => candidateNamespace === namespace,
                ).map(
                    ([
                        candidateNamespace,
                        memberName,
                        category,
                        summary,
                        signature,
                        link,
                    ]) =>
                        createItem(
                            memberName,
                            `unc ${category}`,
                            summary,
                            signature,
                            link,
                            {
                                kind: signature.startsWith("namespace ")
                                    ? "namespace"
                                    : memberName === "Fonts"
                                      ? "constant"
                                      : "function",
                                namespace: candidateNamespace,
                                score: signature.startsWith("namespace ")
                                    ? 1140
                                    : 1130,
                            },
                        ),
                ),
            ),
    );
