import type { TopLevelDataEntry } from "./uncCompletions.type";

export const UNC_TOP_LEVEL_DATA_PART_1 = [
    [
        "cleardrawcache",
        "Drawing",
        "Destroys every drawing object in the cache. Invalidates references to the drawing objects.",
        "function cleardrawcache(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "getrenderproperty",
        "Drawing",
        "Gets the value of a property of a drawing. Functionally identical to drawing[property].",
        "function getrenderproperty(drawing: Drawing, property: string): any",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "isrenderobj",
        "Drawing",
        "Returns whether the given object is a valid Drawing.",
        "function isrenderobj(object: any): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "setrenderproperty",
        "Drawing",
        "Sets the value of a property of a drawing. Functionally identical to drawing[property] = value.",
        "function setrenderproperty(drawing: Drawing, property: string, value: any): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "cloneref",
        "cache",
        "Returns a copy of the Instance reference to object. This is useful for managing an Instance without directly referencing it.",
        "function cloneref(object: Instance): Instance",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "compareinstances",
        "cache",
        "Returns whether objects a and b both reference the same Instance.",
        "function compareinstances(a: Instance, b: Instance): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "checkcaller",
        "closures",
        "Returns whether the function currently running was called by the executor.",
        "function checkcaller(): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "clonefunction",
        "closures",
        "Generates a new closure based on the bytecode of function func.",
        "clonefunction<T>(func: T): T",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "getcallingscript",
        "closures",
        "Returns the script responsible for the currently running function.",
        "function getcallingscript(): BaseScript",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "hookfunction",
        "closures",
        "Replaces func with hook internally, where hook will be invoked in place of func when called.",
        "function hookfunction<T>(func: T, hook: function): T",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "iscclosure",
        "closures",
        "Returns whether or not func is a closure whose source is written in C.",
        "function iscclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "islclosure",
        "closures",
        "Returns whether or not func is a closure whose source is written in Luau.",
        "function islclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "isexecutorclosure",
        "closures",
        "Returns whether or not func was created by the executor.",
        "function isexecutorclosure(func: function): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "loadstring",
        "closures",
        "Generates a chunk from the given source code. The environment of the returned function is the global environment.",
        "function loadstring(source: string, chunkname: string?): (function?, string?)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "newcclosure",
        "closures",
        "Returns a C closure that wraps func. The result is functionally identical to func, but identifies as a C closure, and may have different metadata.",
        "function newcclosure<T>(func: T): T",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/closures.md",
    ],
    [
        "rconsoleclear",
        "console",
        "Clears the output of the console window.",
        "function rconsoleclear(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsolecreate",
        "console",
        "Opens the console window. Text previously output to the console will not be cleared.",
        "function rconsolecreate(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsoledestroy",
        "console",
        "Closes the console window and clears its output. The title will not be changed.",
        "function rconsoledestroy(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsoleinput",
        "console",
        "Waits for the user to input text into the console window. Returns the result.",
        "function rconsoleinput(): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsoleprint",
        "console",
        "Prints text to the console window. Does not clear existing text or create a new line.",
        "function rconsoleprint(text: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "rconsolesettitle",
        "console",
        "Sets the title of the console window to title.",
        "function rconsolesettitle(title: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/console.md",
    ],
    [
        "readfile",
        "filesystem",
        "Returns the contents of the file located at path.",
        "function readfile(path: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "listfiles",
        "filesystem",
        "Returns a list of files and folders in the folder located at path. The returned list contains whole paths.",
        "function listfiles(path: string): {string}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "writefile",
        "filesystem",
        "Writes data to the file located at path if it is not a folder.",
        "function writefile(path: string, data: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "makefolder",
        "filesystem",
        "Creates a folder at path if it does not already exist.",
        "function makefolder(path: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "appendfile",
        "filesystem",
        "Appends data to the end of the file located at path. Creates the file if it does not exist.",
        "function appendfile(path: string, data: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "isfile",
        "filesystem",
        "Returns whether or not path points to a file.",
        "function isfile(path: string): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "isfolder",
        "filesystem",
        "Returns whether or not path points to a folder.",
        "function isfolder(path: string): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "delfile",
        "filesystem",
        "Removes the file located at path.",
        "function delfile(path: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "delfolder",
        "filesystem",
        "Removes the folder located at path.",
        "function delfolder(path: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "loadfile",
        "filesystem",
        "Generates a chunk from the file located at path. The environment of the returned function is the global environment.",
        "function loadfile(path: string, chunkname: string?): (function?, string?)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "dofile",
        "filesystem",
        "Attempts to load the file located at path and execute it on a new thread.",
        "function dofile(path: string): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/filesystem.md",
    ],
    [
        "isrbxactive",
        "input",
        "Returns whether the game's window is in focus. Must be true for other input functions to work.",
        "function isrbxactive(): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
    [
        "mouse1click",
        "input",
        "Dispatches a left mouse button click.",
        "function mouse1click(): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/input.md",
    ],
] as const satisfies readonly TopLevelDataEntry[];
