import type { NamespaceDataEntry } from "./uncCompletions.type";

export const UNC_NAMESPACE_DATA = [
    [
        "Drawing",
        "new",
        "Drawing",
        "Create a new drawing object of the specified type.",
        "function Drawing.new(type: string): Drawing",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "Drawing",
        "Fonts",
        "Drawing",
        "A table containing the available font names. The style of each font varies depending on the executor.",
        "Drawing.Fonts: { [string]: number }",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/Drawing.md",
    ],
    [
        "WebSocket",
        "connect",
        "WebSocket",
        "Establishes a WebSocket connection to the specified URL.",
        "function WebSocket.connect(url: string): WebSocket",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/WebSocket.md",
    ],
    [
        "cache",
        "invalidate",
        "cache",
        "Deletes object from the Instance cache. Effectively invalidates object as a reference to the underlying Instance.",
        "function cache.invalidate(object: Instance): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "cache",
        "iscached",
        "cache",
        "Checks whether object exists in the Instance cache.",
        "function cache.iscached(object: Instance): boolean",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "cache",
        "replace",
        "cache",
        "Replaces object in the Instance cache with newObject.",
        "function cache.replace(object: Instance, newObject: Instance): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/cache.md",
    ],
    [
        "crypt",
        "base64",
        "crypt",
        "UNC nested namespace for Base64 helpers under crypt.",
        "namespace crypt.base64",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "base64encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function crypt.base64encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "base64decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function crypt.base64decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "base64_encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function crypt.base64encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "base64_decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function crypt.base64decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "encrypt",
        "crypt",
        "Encrypts an unencoded string using AES encryption. Returns the base64 encoded and encrypted string, and the IV.",
        "function crypt.encrypt(data: string, key: string, iv: string?, mode: string?): (string, string)",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "decrypt",
        "crypt",
        "Decrypts the base64 encoded and encrypted content. Returns the raw string.",
        "function crypt.decrypt(data: string, key: string, iv: string, mode: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "generatebytes",
        "crypt",
        "Generates a random sequence of bytes of the given size. Returns the sequence as a base64 encoded string.",
        "function crypt.generatebytes(size: number): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "generatekey",
        "crypt",
        "Generates a base64 encoded 256-bit key. The result can be used as the second parameter for the crypt.encrypt and crypt.decrypt functions.",
        "function crypt.generatekey(): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt",
        "hash",
        "crypt",
        "Returns the result of hashing the data using the given algorithm.",
        "function crypt.hash(data: string, algorithm: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt.base64",
        "encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function crypt.base64.encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "crypt.base64",
        "decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function crypt.base64.decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "debug",
        "getconstant",
        "debug",
        "Returns the constant at index in the constant table of the function or level func. Throws an error if the constant does not exist.",
        "function debug.getconstant(func: function | number, index: number): any",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getconstants",
        "debug",
        "Returns the constant table of the function or level func.",
        "function debug.getconstants(func: function | number): {any}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getinfo",
        "debug",
        "Returns debugger information about a function or stack level.",
        "function debug.getinfo(func: function | number): DebugInfo",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getproto",
        "debug",
        "Returns the proto at index in the function or level func if active is false.",
        "function debug.getproto(func: function | number, index: number, active: boolean?): function | {function}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getprotos",
        "debug",
        "Returns a list of protos of the function or level func.",
        "function debug.getprotos(func: function | number): {function}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getstack",
        "debug",
        "Returns the value at index in the stack frame level. Throws an error if no value could be found.",
        "function debug.getstack(level: number, index: number?): any | {any}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getupvalue",
        "debug",
        "Returns the upvalue at index in the function or level func. Throws an error if the upvalue does not exist.",
        "function debug.getupvalue(func: function | number, index: number): any",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "getupvalues",
        "debug",
        "Returns a list of upvalues of the function or level func.",
        "function debug.getupvalues(func: function | number): {any}",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "setconstant",
        "debug",
        "Sets the constant at index in the function or level func to value.",
        "function debug.setconstant(func: function | number, index: number, value: any): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "setstack",
        "debug",
        "Sets the register at index in the stack frame level to value.",
        "function debug.setstack(level: number, index: number, value: any): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "debug",
        "setupvalue",
        "debug",
        "Sets the upvalue at index in the function or level func to value.",
        "function debug.setupvalue(func: function | number, index: number, value: any): ()",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/debug.md",
    ],
    [
        "base64",
        "encode",
        "crypt",
        "Encodes a string of bytes into Base64.",
        "function base64.encode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "base64",
        "decode",
        "crypt",
        "Decodes a Base64 string to a string of bytes.",
        "function base64.decode(data: string): string",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/crypt.md",
    ],
    [
        "http",
        "request",
        "misc",
        "Sends an HTTP request using the specified options. Yields until the request is complete, and returns the response.",
        "function http.request(options: HttpRequest): HttpResponse",
        "https://github.com/unified-naming-convention/NamingStandard/blob/main/api/misc.md",
    ],
] as const satisfies readonly NamespaceDataEntry[];
